Add kwack - In-Memory Analytics for Kafka using DuckDB
davidgasquez/awesome-duckdb pull request #125
Opened 2024-07-11 19:03 UTC by rayokota

2024-07-12 09:16 UTC, davidgasquez requested changes
Thanks for the PR! 

Added a small suggestion to please the linter.

2024-07-12 09:16 UTC, davidgasquez commented on README.md
> +- [kwack](https://github.com/rayokota/kwack) - In-Memory Analytics for Kafka using DuckDB
```suggestion
- [kwack](https://github.com/rayokota/kwack) - In-Memory Analytics for Kafka using DuckDB.
```

2024-07-12 15:36 UTC, rayokota commented
Thanks @davidgasquez , committed your suggestion

2024-07-15 09:51 UTC, davidgasquez approved these changes
Sweet! Merging it now.

2024-07-15 09:52 UTC, merged